### ISSUE TITLE
Providers only actually work in tests

### ISSUE THREAD

**Issue by leepa** [arista-eosplus/puppet-eos#60]
```
Error: Could not autoload puppet/type/eos_user: Could not autoload puppet/provider/eos_user/default: undefined method `version' for nil:NilClass
```

This is because the confine relies on the gem already being required somewhere once. Obviously tests are fine as the spec_helper loads the rbeapi gem - but nothing else does.

**Comment by jerearista** [comment]
Lee,
  Can you provide a little more info on the environment in which you are seeing an issue and from what commit ID you pulled in develop?   Specifically, are you using Puppet open-source or enterprise and what version?    I'm looking to this same issue with an older version of Puppet Enterprise right now.

The way this works is through the use of puppet "features" which are sync'ed to the agents by pluginsync.  When the confine statement checks for the rbeapi feature the first time, rbeapi gets loaded.  This check may be performed several times, automatically, during a single puppet run meaning that the rubygem/swix can be installed by puppet, then later used in the same run.

Rbeapi must be manually loaded for the spec tests as the feature plugins aren't in effect, there.

**Comment by leepa** [comment]
I had this problem on the latest vEOS Vagrant Box image. Obviously I'm locally applying and not using a Master in this case. So the version is the version of the .swix from puppetlabs as there's no other one to download?

If I add the require statement to the providers, it works again. So the confine statement is most certainly not auto-loading anything for me on vEOS itself.

**Comment by jerearista** [comment]
Thanks.  I am going to back out the version confinement from the coming release until we can do some more testing with additional environments.   

The puppet agent version can be found in the SWIX file you downloaded ('show extensions') or by running 'puppet --version'. PuppetLabs has provided agent packages for EOS since 3.7.  However, the fact that you are running masterless is the most significant thing for me.  Since there's no pluginsync running in headless mode, I'm curious, have you installed the rbeapi feature to `sudo puppet config print libdir`/puppet/feature/rbeapi.rb ?

I have recreated this in my masterless environment so I can work on this in the future.

**Comment by leepa** [comment]
I installed the gem (although compiled it myself) using `/opt/puppetlabs/puppet/bin/gem install rbeapi-3.0.0.gem` because otherwise the new User support and the like isn't there.

Essentially the use case here is using Vagrant to test puppet setups before going to production - we do it with servers... and having a team able to do that with network devices too is appealing.

Glad you were able to repro.

**Comment by jerearista** [comment]
I absolutely agree.    In regard to the pre-release code you're running, I'm trying to wrap up some final details and get both of those released this week so I welcome your feedback.  The  confinement-update branch has the version check removed and confinement added to 2 new providers.

**Comment by jerearista** [comment]
I've removed the rbeapi version confinement from the 1.3.0 release of the puppet providers.   We will review this capability at another time.  Thanks for the feedback.
