### ISSUE TITLE
Wrong datatype ine trunk_groups

### ISSUE THREAD

**Issue by mmailand** [arista-eosplus/puppet-eos#79]
If I want to create this resource
  eos_vlan { '4094':
    enable       => true,
    vlan_name    => 'MLAG_control',
    trunk_groups => ['trunkpeer'],
  }
 with this patch applied #78. There is still a missmatch in the datatype.
The config on the switch in the running-config shows.

vlan 4094
   name MLAG_control
   trunk group {:value=>["trunkpeer"]}

This looks like an array string missmatch, but I cannot find where.
Any help would be appreciated

Best Regards, 
martin

**Comment by devrobo** [comment]
Thanks for catching this problem. We need to get automated system tests running on jenkins. Currently porting our system tests to beaker.

**Comment by mmailand** [comment]
Hi,
that's great to hear. How could I help, where is the communications for this module?
Is there mailinglist / irc channel?

**Comment by devrobo** [comment]
The problem occurs because the parameters to add_trunk_group are positional. So the call should look like:

node.api('vlans').add_trunk_group(resource[:vlanid], value)

The 2nd bug in the provider trunk_groups method is that an array is passed in but add_trunk_group call in rbeapi only takes a string so we need to iterate over all the trunk groups being passed in. I am generating a pull request with the fixes.

**Comment by devrobo** [comment]
While my previous analysis was correct with respect to why the tests were failing it was not correct with respect to puppet semantics. We need to define set_trunk_groups in the vlan api in rbeapi because in puppet we need to be able to deterministically set the trunk groups to an array of values. I am going to close this issue because it was created by PR #78 and I am going to make the necessary modifications to rbeapi.
